theme = "github_dark_high_contrast"

[editor]
line-number = "relative"
mouse = false
auto-pairs = false
cursorline = true
auto-format = true
rulers = [120]
true-color = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-name", "version-control", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.smart-tab]
enable = false

[editor.lsp]
auto-signature-help = false
display-messages = true

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
"A-x" = "extend_to_line_bounds"
"X" = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
"A-x"  ="extend_to_line_bounds"
"X" = ["extend_line_up", "extend_to_line_bounds"]
