theme = "github_dark_high_contrast"

[editor]
line-number = "relative"
mouse = false
auto-pairs = false
cursorline = true
auto-format = true

[editor.cursor-shape]
normal = "block"
insert = "bar"

[editor.statusline]
left = ["mode", "file-modification-indicator", "read-only-indicator", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.smart-tab]
enable = false
